[colors]
foreground = "#00d4b1"
background = "#101116"
cursor_bg = "#00d4b1"
cursor_fg = "#101116"
selection_bg = "#311b92"
selection_fg = "#00d4b1"
scrollbar_thumb = "#029b60"
split = "#00d4b1"

[colors.ansi]
black = "#10d4b0"
red = "#940303"
green = "#0059ff"
yellow = "#1a1b03"
blue = "#004cf1"
magenta = "#94058a"
cyan = "#029790"
white = "#311b92"

[colors.brights]
black = "#02adf1"
red = "#be0000"
green = "#00ff9c"
yellow = "#d0f30c"
blue = "#00a2ff"
magenta = "#e215d4"
cyan = "#08e1d7"
white = "#2eb8f8"
