[colors]
foreground = "#00d4b1"
background = "#101116"
cursor_bg = "#00d4b1"
cursor_fg = "#101116"
selection_bg = "#311b92"
selection_fg = "#00d4b1"
scrollbar_thumb = "#029b60"
split = "#00d4b1"

ansi = [
  "#10d4b0",  # black
  "#ff7edb",  # red (Synthwave pink)
  "#0059ff",  # green
  "#f3e70f",  # yellow
  "#0088ff",  # blue
  "#94058a",  # magenta
  "#029790",  # cyan
  "#311b92",  # white
]

brights = [
  "#02adf1",  # black
  "#ff6b9d",  # red (bright pink)
  "#00ff9c",  # green
  "#d0f30c",  # yellow
  "#00a2ff",  # blue
  "#e215d4",  # magenta
  "#08e1d7",  # cyan
  "#2eb8f8",  # white
]
